#!/usr/bin/env python3
"""Regenerate DIFF-t7d410f66.md: the before/after diff of the venue announcements.

Card t_7d410f66. Compares the artifacts as they stood before the card (kept in
`before-t7d410f66/`) with the current ones, at the level a CLIENT sees them: each
event's `content` parsed back from its JSON string.

    python3 evidence/announcements/gen-diff-t7d410f66.py

Regenerate the current artifacts first with:
    deno run --allow-read --allow-net --allow-write tools/emit-venue-announcement.ts \
      --venue venues/<slug>/venue.json --kind <11316|11317> --dry-run
"""
import difflib
import json
import pathlib

HERE = pathlib.Path(__file__).resolve().parent
BEFORE = HERE / "before-t7d410f66"
SLUGS = ("doppelt-kaese-berlin", "pizza-e-pasta-ruedesheimerplatz")
KINDS = ("11316", "11317")


def main() -> int:
    out: list[str] = []
    add = out.append
    add("# Before/after diff — the venue announcements the delivery-area fix changes")
    add("")
    add("Card `t_7d410f66`. Generated by `evidence/announcements/gen-diff-t7d410f66.py`")
    add("from the artifacts kept in `before-t7d410f66/` (the announcements as they")
    add("stood before this card) against the current ones — reproduce the latter with")
    add("`tools/emit-venue-announcement.ts --dry-run`.")
    add("")
    add("Each artifact is a CEP-6 event whose `content` is a JSON **string**. The diff")
    add("below is of the parsed content, so it shows what a client actually sees.")
    add("")

    for kind in KINDS:
        for slug in SLUGS:
            b = json.loads((BEFORE / f"{slug}.{kind}.json").read_text(encoding="utf-8"))
            a = json.loads((HERE / f"{slug}.{kind}.json").read_text(encoding="utf-8"))
            bc, ac = json.loads(b["content"]), json.loads(a["content"])
            bl = json.dumps(bc, ensure_ascii=False, indent=2, sort_keys=True).splitlines()
            al = json.dumps(ac, ensure_ascii=False, indent=2, sort_keys=True).splitlines()
            d = list(difflib.unified_diff(bl, al, "before", "after", lineterm="", n=3))
            bf, af = bc.get("fulfilment", {}), ac.get("fulfilment", {})
            tags_changed = b.get("tags") != a.get("tags")
            added_tags = [t for t in (a.get("tags") or []) if t not in (b.get("tags") or [])]

            add(f"## {slug} — kind {kind}")
            add("")
            add(f"- `fulfilment` block changed: **{bf != af}**")
            add(f"- tag set changed: **{tags_changed}**")
            add(f"- parsed-content diff lines: {len(d)}")
            add("")
            if d:
                add("```diff")
                out.extend(d)
                add("```")
                add("")
            add("delivery block AFTER:")
            add("")
            add("```json")
            add(json.dumps(af.get("delivery"), ensure_ascii=False, indent=2, sort_keys=True))
            add("```")
            add("")
            if tags_changed:
                add(f"tags added: `{json.dumps(added_tags, ensure_ascii=False)}`")
                add("")
                add("That addition is the emitter drift from ADR-0011 (the declared order")
                add("inputs `order.items` / `order.when`), which the committed artifacts")
                add("predate. It is **not** part of the delivery-area fix; republishing")
                add("carries it along, so it is recorded here rather than left implicit.")
                add("")

    (HERE / "DIFF-t7d410f66.md").write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {HERE / 'DIFF-t7d410f66.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
